name: app_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  # supabase
  supabase_flutter: ^1.10.25
  provider: ^6.1.1
  image_picker: ^1.0.7
  http: ^1.1.0
  file_picker: ^5.2.10
  sign_in_with_apple: ^5.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
